services:
  - type: worker
    name: prism-bot
    env: docker
    envVars:
      - key: BOT_TOKEN
        value: 7916791327:AAECH7DT9Oa-8O_PSGbW-YkFyNwc2hTvJ9I
      - key: BTC_ADDRESS
        value: bc1qdtngv6cwgh502pf726lef6632cza9d5s54x56m
      - key: DATABASE_URL
        fromDatabase:
          name: prism-db
          property: connectionString
databases:
  - name: prism-db
    plan: free
